// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 10:02:11 PM CST 

package com.redhat.poc.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EKSEKS01 }
     * 
     */
    public EKSEKS01 createEKSEKS01() {
        return new EKSEKS01();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC }
     * 
     */
    public EKSEKS01.IDOC createEKSEKS01IDOC() {
        return new EKSEKS01 .IDOC();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY createEKSEKS01IDOCE1PISTY() {
        return new EKSEKS01 .IDOC.E1PISTY();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHO }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHO createEKSEKS01IDOCE1PISTYE1PISHO() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHO();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHO.E1PISIO }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHO.E1PISIO createEKSEKS01IDOCE1PISTYE1PISHOE1PISIO() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHO.E1PISIO();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHD }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHD createEKSEKS01IDOCE1PISTYE1PISHD() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHD();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHD.E1PISIT }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHD.E1PISIT createEKSEKS01IDOCE1PISTYE1PISHDE1PISIT() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHD.E1PISIT();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.EDIDC40 }
     * 
     */
    public EKSEKS01.IDOC.EDIDC40 createEKSEKS01IDOCEDIDC40() {
        return new EKSEKS01 .IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1CMCCO }
     * 
     */
    public EKSEKS01.IDOC.E1CMCCO createEKSEKS01IDOCE1CMCCO() {
        return new EKSEKS01 .IDOC.E1CMCCO();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHO.E1PISIO.E1PISSO }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHO.E1PISIO.E1PISSO createEKSEKS01IDOCE1PISTYE1PISHOE1PISIOE1PISSO() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHO.E1PISIO.E1PISSO();
    }

    /**
     * Create an instance of {@link EKSEKS01 .IDOC.E1PISTY.E1PISHD.E1PISIT.E1PISSI }
     * 
     */
    public EKSEKS01.IDOC.E1PISTY.E1PISHD.E1PISIT.E1PISSI createEKSEKS01IDOCE1PISTYE1PISHDE1PISITE1PISSI() {
        return new EKSEKS01 .IDOC.E1PISTY.E1PISHD.E1PISIT.E1PISSI();
    }

}
